### ISSUE TITLE
godot_bind Wlambda dependency missing

### ISSUE THREAD

**Issue by meldron** [WeirdConstructor/sscg#3]
Hi there,

I wanted to check out your game, but building the rust objects fails because
you are using a custom wlambda create included from a directory which is not tracked in this repo:

```toml
wlambda     = { path = "../../WLambda" }
```

Can you tell me why you aren't using the one from crates.io?

Thanks a lot!

P.S. game looks nice!

**Comment by WeirdConstructor** [comment]
I'm using a local checkout of WLambda because it's usually slightly ahead of the crates.io
version. That is because I extend WLambda with missing functionality while I stumble across it when developing SSCG.

I suggest using the github version of WLambda for the meantime.

Sorry for the late reply, I've been quite busy with developing WLambda the last months.
